### ISSUE TITLE
Physical keys interaction

### ISSUE THREAD

**Issue by ad31c0** [stanford-oval/genie-client-cpp#15]
Connect the physical keys, as defined through KEY_CODES in the configuration file to the correct functionalities.

Proposed behavior is the following:
- vol+ = Master Volume +10%
- vol- = Master Volume -10%
- mute = Mute or Unmute the Microphone
- play = Stop or Resume audio pipeline or music

Contemporary press of:
- vol+ / vol- = Switch the device to configuration mode
- all four buttons = Speak the current IP address of the Wireless interface

**Comment by gcampax** [comment]
This was implemented, except the configuration modes.
