### ISSUE TITLE
Replays old messages at startup

### ISSUE THREAD

**Issue by ad31c0** [stanford-oval/genie-client-cpp#4]
At startup when it connects to the cloud, the cloud server will replay a short sequence of old messages. These messages are not relevant and should not be played. The options to solve it are the following:
1) We might need to store the ID of the last played message to disk or similar for this purpose.
2) Add a new parameter on the WS API to decide whether the cloud should replay the history upon client connection.

**Comment by nrser** [comment]
For a first step let's just save the last seen ID in memory and not replay messages at or before that
